[package]
name = "trust-80"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.2"
sdl2-unifont = { git = "https://github.com/carlalbrecht/sdl2-unifont", rev = "070438cedca60b60fb0234b19e581bef1e6ac1f6" }
zilog_z80 = "0.6.0"