//! Host-independent key identifiers, named after and mirroring SDL2's own
//! `Keycode` (the character a key produces, already layout/shift-resolved
//! by the host) - but these aren't SDL2's types, so `keyboard.rs`'s matrix
//! logic doesn't depend on it. Named after bytebox_core::keys, which solves
//! the exact same problem for the same reason: a frontend that isn't SDL2
//! (a future web/wasm build, which can't link SDL2 at all) needs to drive
//! the same matrix logic through its own translation into this enum instead.
//!
//! Only the variants `keyboard.rs`'s matrix mapping actually uses are
//! present - trimmed to what's needed, not a full copy of SDL2's Keycode.

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub enum Keycode {
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    Kp0,
    Kp1,
    Kp2,
    Kp3,
    Kp4,
    Kp5,
    Kp6,
    Kp7,
    Kp8,
    Kp9,
    KpAt,
    KpPercent,
    KpAmpersand,
    KpLeftParen,
    KpRightParen,
    KpColon,
    KpMultiply,
    KpPlus,
    KpComma,
    KpLess,
    KpMinus,
    KpEquals,
    KpPeriod,
    KpGreater,
    KpDivide,
    KpEnter,
    At,
    Exclaim,
    Quotedbl,
    Hash,
    Dollar,
    Percent,
    Ampersand,
    Quote,
    LeftParen,
    RightParen,
    Colon,
    Asterisk,
    Semicolon,
    Plus,
    Comma,
    Less,
    Minus,
    Equals,
    Period,
    Greater,
    Slash,
    Question,
    Return,
    Home,
    End,
    /// Real TRS-80 Model I key sharing Home's own matrix position (row
    /// 0x3840, bit 0x02) - see `key_target`'s doc comment.
    Clear,
    /// Real TRS-80 Model I key sharing End's own matrix position (row
    /// 0x3840, bit 0x04) - see `key_target`'s doc comment.
    Break,
    Up,
    Down,
    Left,
    Right,
    Backspace,
    Space,
    LShift,
    RShift,
    LCtrl,
    RAlt,
}
