[display]
width = 1024
height = 768
font = "assets/AnotherMansTreasureMIB64C2X3Y.ttf"
font_size = 48

[memory]
rom = "bin/level2.rom"
ram = 0xFFFF

[storage]
tape_path = "bin/"

[keyboard]
repeat_delay = 100
keypress_timeout = 8
memclear_delay = 6

[debug]
iodevices = false
