// One-time dev tool: rasterizes the 256 TRS-80 character codes from the
// AnotherMansTreasure font (which maps them 1:1 into a private-use-area
// block starting at 0xE000, matching what src/display.rs used for SDL_ttf
// rendering before this tool existed) into a fixed-size bitmap per
// character, baking in the font's own antialiasing once, offline, instead
// of shaping text through FreeType every frame (which also isn't available
// at all in a wasm/browser build).
//
// Cell shape (18x54) is chosen so the 64x16 character grid comes out to an
// exact 4:3 buffer (1152x864): the TRS-80's real 384x192 hardware
// resolution is a 2:1 buffer stretched by non-square CRT pixels onto a 4:3
// tube, which this reproduces by using non-square (1:3) cells instead of
// trying to replicate the hardware's actual pixel dimensions - much
// higher-resolution glyphs than real hardware had, so text stays smooth
// looking here rather than reproducing individual chunky hardware pixels.
//
// Run with `cargo run --example gen_charset > src/charset.rs` and check the
// output visually (via the app) before committing - this isn't run at
// build time, its output is committed source.

const CELL_W: usize = 18;
const CELL_H: usize = 54;
const FONT_SIZE: u16 = 48; // gives font.height() == 48, vertically centered
// in the 54-tall cell (3px top/bottom margin).
const Y_OFFSET: usize = (CELL_H - FONT_SIZE as usize) / 2;

fn main() {
    let ttf = sdl2::ttf::init().unwrap();
    let font = ttf
        .load_font("assets/AnotherMansTreasureMIB64C2X3Y.ttf", FONT_SIZE)
        .unwrap();

    println!("// Generated by examples/gen_charset.rs - do not hand-edit.");
    println!("// 256 TRS-80 character codes, each a {CELL_W}x{CELL_H} intensity bitmap");
    println!("// (row-major, one byte per pixel: 0 = background, 255 = full ink).");
    println!("pub const CELL_W: usize = {CELL_W};");
    println!("pub const CELL_H: usize = {CELL_H};");
    println!("pub const CHARSET: [[u8; CELL_W * CELL_H]; 256] = [");

    for code in 0u32..256 {
        let ch = char::from_u32(0xE000 + code).unwrap();
        let mut cell = [0u8; CELL_W * CELL_H];

        // Space and other blank codes: render() errors or returns an empty
        // surface for some codes in this font - leave those cells blank
        // rather than aborting the whole generation.
        if let Ok(surf) = font.render_char(ch).blended(sdl2::pixels::Color::RGBA(255, 255, 255, 255)) {
            if let Ok(surf) = surf.convert_format(sdl2::pixels::PixelFormatEnum::RGBA32) {
                let pitch = surf.pitch() as usize;
                let w = (surf.width() as usize).min(CELL_W);
                let h = (surf.height() as usize).min(FONT_SIZE as usize);
                surf.with_lock(|pixels| {
                    for y in 0..h {
                        for x in 0..w {
                            let alpha = pixels[y * pitch + x * 4 + 3];
                            cell[(Y_OFFSET + y) * CELL_W + x] = alpha;
                        }
                    }
                });
            }
        }

        print!("    [");
        for (i, b) in cell.iter().enumerate() {
            if i > 0 {
                print!(",");
            }
            print!("{b}");
        }
        println!("], // {code:#04X}");
    }
    println!("];");
}
